### PR TITLE
Fix render methods to make both components controlled.

### PR DESCRIPTION
**Pull request by bebbi**
External updates to value are now reflected in the dropdowns.

This should address #12

### CODE REVIEW

**Comment by tchaffee** [comment]
This will not work for the region dropdown if the country is supplied to the region dropdown like this:

```
<RegionDropdown
  id="formControlsSelect"
  classes="form-control"
  country="US"
  name="region"
  countryValueType="short"
  value={region}
  labelType="short"
  valueType="short"
  onChange={(val) => this.selectRegion(val)}
/>
```
Because of the code in `shouldComponentUpdate`, which needs to be something like this, since the country never changes and the component will therefore never be re-rendered when the `value` changes.

```
shouldComponentUpdate (nextProps) {
  return (nextProps.country !== this.props.country) || (nextProps.value !== this.props.value);
}
```

**Comment by bebbi** [comment]
That's the point of controlled components.
The country should come from a source that's always reflecting current state.

**Comment by bebbi** [comment]
Sorry, you're right, I missed your second part.
Did you test your solution? I can add to the PR.

**Comment by bebbi** [comment]
It appears to work..

**Comment by tchaffee** [comment]
I did test it, and it worked for me.

**Comment by benkeen** [comment]
Thanks, @bebbi! Your fix looks good. I'm totally swamped tonight but I'll test it out tomorrow and get a fresh version out the door. Appreciated!

**Comment by bebbi** [comment]
Very appreciated @benkeen. And thanks @tchaffee for the collab.

**Pull request merged**
